### ISSUE TITLE
Compilation errors after merging pull-request #23

### ISSUE THREAD

**Issue by AtiyahElsheikh** [OpenModelica/BioChem#25]
After the changes in[ pull-request # 23](https://github.com/OpenModelica/BioChem/pull/23) in the develop branch, I was able to compile with OMC 1.17.0. However it not compiling with OMC 1.18.0. 

Found out later that examples don't compile. The message of the compiler error is as follows: 

[1] 12:11:56 Translation Error
[BioChem.Units: 9:3-12:13]: A class extending from builtin type Volume_litre may not have other elements.

I also found similar errors when compiling types within Icons.Units, e.g. compiling TypeRealBase produces the error

[BioChem.Icons.Units.TypeRealBase: 3:1-7:17]: Type ‘TypeRealBase‘ does not extend a basic type.

Diving into Modelica specificatio[n (Sec. 7.1.3) ](https://specification.modelica.org/maint/3.5/inheritance-modification-and-redeclaration.html), I done a mistake by extending a type from a model. This is not allowed. 

Going to fix that.
